name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Wait for MongoDB to be ready
      run: |
        echo "Waiting for MongoDB to start..."
        timeout 30s bash -c 'until nc -z localhost 27017; do sleep 2; done'
        echo "MongoDB is ready!"
      
    - name: Run tests
      run: npm test
      env:
        NODE_ENV: test